### ISSUE TITLE
Any chance of getting support for PNG and HEIC?

### ISSUE THREAD

**Issue by Martibis** [bigflood/dartexif#15]

**Comment by bigflood** [comment]
maybe HEIC, but not PNG.

**Comment by abulka** [comment]
Curious why `PNG` cannot be supported? Various other programs can read it OK. 

The dart package https://pub.dev/packages/metadata can also read it (but it doesn't support null safety yet so I can't use it).

**Comment by TheLastGimbus** [comment]
Yeah, `PNG`s do not officialy have exifs, but *some* of them do/there are some hacks to do it i think?

**Comment by gwanhyeong** [comment]
I tried.
https://github.com/bigflood/dartexif/pull/41

**Comment by TheLastGimbus** [comment]
Waiting for HEIC now :crossed_fingers:
