### ISSUE TITLE
Jpg issue 

### ISSUE THREAD

**Issue by ludoo0d0a** [bigflood/dartexif#22]
I receive a *No exif information* exception for this picture:
https://user-images.githubusercontent.com/16626063/117620390-c08f4380-b170-11eb-8630-ff300692695a.jpg

with this tool (http://exif.regex.info/exif.cgi), data are read correctly.

Do you think you can investigate ?
I tried but i'm a bit lost in the middle of the code/specs

Thanks

```
JFIF

JFIF Version	1.01
Resolution	300 pixels/inch
File — basic information derived from the file.

File Type	JPEG
File Type Extension	jpg
MIME Type	image/jpeg
Encoding Process	Progressive DCT, Huffman coding
Bits Per Sample	8
Color Components	3
File Size	72 kB
Image Size	853 × 480
Y Cb Cr Sub Sampling	YCbCr4:2:0 (2 2)
Composite
This block of data is computed based upon other items. Some of it may be wildly incorrect, especially if the image has been resized.

Megapixels	0.409
```

**Comment by bigflood** [comment]
I think it is corrupt file.

no exif data found with these tool:
- https://github.com/ianare/exif-py
- https://github.com/Exiv2/exiv2

**Comment by ludoo0d0a** [comment]
Ok 
Thanks for having check this.
