### ISSUE TITLE
Exif data, why can the map key be null?

### ISSUE THREAD

**Issue by jimmyff** [bigflood/dartexif#23]
```Future<Map<String?, IfdTag>?> readExifFromBytes```

I'm not sure why you would expect an `IfdTag` with a null key?

```Future<Map<String, IfdTag>?> readExifFromBytes``` is what I would assume to be correct?

**Comment by bigflood** [comment]
You are right.
So, I'm currently refactoring the code.

`Future<Map<String?, IfdTag>?>` → `Future<Map<String, IfdTag>>`

https://github.com/bigflood/dartexif/blob/refactoring/lib/src/read_exif.dart#L20
