### ISSUE TITLE
not getting latitude and longitude from image

### ISSUE THREAD

**Issue by ajinkya446** [bigflood/dartexif#27]
Can not able to get LatLng co-ordinate from image using exif.

![image](https://user-images.githubusercontent.com/49361315/135711785-7dc7374b-f6b1-4397-82ff-538924d40fdc.png)

Getting 58 map items but can't able to find LatLng co-ordinates also tried with GPS as well.
        final latRef = data['GPS GPSLatitudeRef']?.toString();
        print("ref"+latRef.toString());
        var latVal = gpsValuesToFloat(data['GPS GPSLatitude']?.values);

Bu it is giving null values from exif

**Comment by bigflood** [comment]
@ajinkya446 
I will helpful if you upload the image file.

**Comment by ajinkya446** [comment]
> @ajinkya446 It will helpful if you upload the image file.
The issue is resolved because it is showing null data for latitude and longitude on image and but after adding Exif data on image using native Android and iOS code in flutter it resolved the issue. After that the same image contains the EXIF data with GPS latlng cordinates.
