### ISSUE TITLE
readExifFromFile: RangeError (end): Invalid value: Only valid value is 0: 4

### ISSUE THREAD

**Issue by ua741** [bigflood/dartexif#29]
**Version:** : 3.0.0
**Partial Stack trace** :
 
    errors.dart in RangeError.checkValidRange at line 338
    array.dart in _List.sublist at line 197
    read_exif.dart in _isTiff at line 186 within exif

https://github.com/bigflood/dartexif/blob/15288d40a196538b5df9d10f66298e3dc40b748f/lib/src/read_exif.dart#L186

**Comment by bigflood** [comment]
@ua741 
Can you upload the image file?

**Comment by bigflood** [comment]
Bug fixed in v3.1.1
