### ISSUE TITLE
Range Error using ReadExifFromBytes

### ISSUE THREAD

**Issue by aenckli** [bigflood/dartexif#31]
Range Error is reported when ReadExifFromBytes read an image file with Exif data having fieldOffset larger than file size or byte array size. The error comes from setPositioinSync in file_interface.dart. There is no bound checking in the function. This does not cause problem using ReadExifFromFile. It may be because file.setPositionSync(position) is more robust in file_interface_io.dart's setPositionSync.

**Comment by bigflood** [comment]
Bug fixed in v3.1.1
