### ISSUE TITLE
there is no any gps information

### ISSUE THREAD

**Issue by winsonet** [bigflood/dartexif#9]
I try to get the GPS information from the image but it seems can't find anythings, what's the key should I take for get the lat/lng info?

thanks!

**Comment by dekoding** [comment]
Same here, and it seems to be specific to iOS. I get GPS information fine on Android:

Information on the iOS simulator:

`[log] Image Orientation (Short): Horizontal (normal)
[log] Image ExifOffset (Long): 38
[log] EXIF ExifImageWidth (Long): 4032
[log] EXIF ExifImageLength (Long): 3024`

Information on Android for the same image:

`[log] Image DateTime (ASCII): 2017:08:21 09:33:37
[log] GPS GPSDOP (Ratio): 19
[log] GPS GPSVersionID (Byte): [2, 2, 0, 0]
[log] GPS GPSDate (ASCII): 2017:08:21
[log] GPS GPSAltitudeRef (Byte): 0
[log] GPS GPSLongitudeRef (ASCII): W
[log] GPS GPSLongitude (Ratio): [122, 16, 4403/100]
[log] GPS GPSProcessingMethod (Undefined): [65, 83, 67, 73, 73, 0, 0, 0, 102, 117, 115, 101, 100]
[log] GPS GPSLatitudeRef (ASCII): N
[log] GPS GPSTimeStamp (Ratio): [16, 33, 37]
[log] GPS GPSAltitude (Ratio): 1065
[log] GPS GPSLatitude (Ratio): [44, 36, 367/20]
[log] Image GPSInfo (Long): 19881
[log] Image Model (ASCII): Pixel XL
[log] Image ImageWidth (Short): 4048
[log] Image ResolutionUnit (Short): Pixels/Inch
[log] Image YCbCrPositioning (Short): Centered
[log] Image ImageLength (Short): 3036
[log] Image YResolution (Ratio): 72
[log] Image Orientation (Short): Horizontal (normal)
[log] Image Software (ASCII): HDR+ 1.0.163413028z
[log] Image ExifOffset (Long): 242
[log] Image XResolution (Ratio): 72
[log] Image Make (ASCII): Google
[log] Thumbnail ImageWidth (Short): 253
[log] Thumbnail ResolutionUnit (Short): Pixels/Inch
[log] Thumbnail ImageLength (Short): 189
[log] Thumbnail YResolution (Ratio): 72
[log] Thumbnail Orientation (Short): Horizontal (normal)
[log] Thumbnail JPEGInterchangeFormatLength (Long): 11254
[log] Thumbnail JPEGInterchangeFormat (Long): 20261
[log] Thumbnail Compression (Short): JPEG (old-style)
[log] Thumbnail XResolution (Ratio): 72
[log] EXIF ColorSpace (Short): sRGB
[log] EXIF FNumber (Ratio): 2
[log] EXIF DateTimeDigitized (ASCII): 2017:08:21 09:33:37
[log] EXIF SubjectDistanceRange (Short): 1
[log] EXIF FocalLength (Ratio): 467/100
[log] EXIF ApertureValue (Ratio): 2
[log] EXIF ExposureMode (Short): Auto Exposure
[log] EXIF SubSecTimeDigitized (ASCII): 257156
[log] EXIF ExifImageLength (Short): 3036
[log] EXIF CustomRendered (Short): Custom
[log] EXIF MaxApertureValue (Ratio): 2
[log] EXIF SceneCaptureType (Short): Standard
[log] EXIF SceneType (Undefined): Directly Photographed
[log] EXIF SubSecTimeOriginal (ASCII): 257156
[log] EXIF Saturation (Short): Normal
[log] EXIF ExposureProgram (Short): Program Normal
[log] EXIF Sharpness (Short): Normal
[log] EXIF WhiteBalance (Short): Auto
[log] EXIF ExifImageWidth (Short): 4048
[log] EXIF ShutterSpeedValue (Signed Ratio): 232/25
[log] EXIF SubSecTime (ASCII): 257156
[log] EXIF MeteringMode (Short): CenterWeightedAverage
[log] EXIF DateTimeOriginal (ASCII): 2017:08:21 09:33:37
[log] EXIF ComponentsConfiguration (Undefined): YCbCr
[log] EXIF SubjectDistance (Ratio): 673/1000
[log] EXIF ExifVersion (Undefined): 0220
[log] EXIF Flash (Short): Flash did not fire, compulsory flash mode
[log] EXIF Contrast (Short): Normal
[log] Interoperability InteroperabilityIndex (ASCII): R98
[log] Interoperability InteroperabilityVersion (Undefined): [48, 49, 48, 48]
[log] EXIF InteroperabilityOffset (Long): 19851
[log] EXIF ExposureBiasValue (Signed Ratio): 0
[log] EXIF BrightnessValue (Signed Ratio): 182/25
[log] EXIF ISOSpeedRatings (Short): 50
[log] EXIF FlashPixVersion (Undefined): 0100
[log] EXIF SensingMethod (Short): One-chip color area
[log] EXIF MakerNote (Undefined): [72, 68, 82, 80, 2, 239, 100, 53, 109, 94, 112, 30, 44, 234, 227, 76, 87, 100, 168, 80, ... ]
[log] EXIF ExposureTime (Ratio): 403/250000
[log] JPEGThumbnail (Proprietary):`

**Comment by pooja96km** [comment]
Has anyone found the solution?

**Comment by ludoo0d0a** [comment]
Same here, GPSlatitude and GPSLongitude are marked as [0,0,0,0]

**Comment by bigflood** [comment]
@ludoo0d0a 

what is your

```
$ dart ./bin/print_exif.dart ../exif-samples/jpg/gps/DSCN0010.jpg 
Opening: ../exif-samples/jpg/gps/DSCN0010.jpg
File has JPEG thumbnail
EXIF ColorSpace (Short): sRGB
EXIF ComponentsConfiguration (Undefined): YCbCr
EXIF Contrast (Short): Normal
EXIF CustomRendered (Short): Normal
EXIF DateTimeDigitized (ASCII): 2008:10:22 16:28:39
EXIF DateTimeOriginal (ASCII): 2008:10:22 16:28:39
EXIF DigitalZoomRatio (Ratio): 0
EXIF ExifImageLength (Long): 480
EXIF ExifImageWidth (Long): 640
EXIF ExifVersion (Undefined): 0220
EXIF ExposureBiasValue (Signed Ratio): 0
EXIF ExposureMode (Short): Auto Exposure
EXIF ExposureProgram (Short): Program Normal
EXIF ExposureTime (Ratio): 1/75
EXIF FNumber (Ratio): 59/10
EXIF FileSource (Undefined): Digital Camera
EXIF Flash (Short): Flash did not fire, compulsory flash mode
EXIF FlashPixVersion (Undefined): 0100
EXIF FocalLength (Ratio): 24
EXIF FocalLengthIn35mmFilm (Short): 112
EXIF GainControl (Short): None
EXIF ISOSpeedRatings (Short): 64
EXIF InteroperabilityOffset (Long): 896
EXIF LightSource (Short): Unknown
EXIF MakerNote (Undefined): [78, 105, 107, 111, 110, 0, 2, 0, 0, 0, 73, 73, 42, 0, 8, 0, 0, 0, 35, 0, ... ]
EXIF MaxApertureValue (Ratio): 29/10
EXIF MeteringMode (Short): Pattern
EXIF Saturation (Short): Normal
EXIF SceneCaptureType (Short): Standard
EXIF SceneType (Undefined): Directly Photographed
EXIF Sharpness (Short): Normal
EXIF SubjectDistanceRange (Short): 0
EXIF UserComment (Undefined): 
EXIF WhiteBalance (Short): Auto
GPS GPSAltitudeRef (Byte): 0
GPS GPSDate (ASCII): 2008:10:23
GPS GPSImgDirectionRef (ASCII): 
GPS GPSLatitude (Ratio): [43, 28, 1407/500]
GPS GPSLatitudeRef (ASCII): N
GPS GPSLongitude (Ratio): [11, 53, 645599999/100000000]
GPS GPSLongitudeRef (ASCII): E
GPS GPSMapDatum (ASCII): WGS-84   
GPS GPSSatellites (ASCII): 06
GPS GPSTimeStamp (Ratio): [14, 27, 181/25]
Image DateTime (ASCII): 2008:11:01 21:15:07
Image ExifOffset (Long): 268
Image GPSInfo (Long): 926
Image ImageDescription (ASCII):                                
Image Make (ASCII): NIKON
Image Model (ASCII): COOLPIX P6000
Image Orientation (Short): Horizontal (normal)
Image ResolutionUnit (Short): Pixels/Inch
Image Software (ASCII): Nikon Transfer 1.1 W
Image XResolution (Ratio): 300
Image YCbCrPositioning (Short): Centered
Image YResolution (Ratio): 300
Interoperability InteroperabilityIndex (ASCII): R98
Interoperability InteroperabilityVersion (Undefined): [48, 49, 48, 48]
MakerNote AFFocusPosition (Undefined): CenterCenterCenterCenter
MakerNote ActiveDLighting (Short): 0
MakerNote AuxiliaryLens (ASCII): OFF         
MakerNote ColorMode (ASCII): COLOR
MakerNote DataDump (Undefined): []
MakerNote DigitalZoomFactor (Ratio): 1
MakerNote FlashSetting (ASCII):        
MakerNote FocusMode (ASCII): AF-S  
MakerNote ISOSelection (ASCII): AUTO  
MakerNote ISOSetting (Short): [0, 0]
MakerNote ImageAdjustment (ASCII): NORMAL       
MakerNote ImageSharpening (ASCII): NORMAL
MakerNote ImageStabilization (ASCII): VR-ON
MakerNote MakernoteVersion (Undefined): 0210
MakerNote NEFBitDepth (Short): [0, 0, 0, 0]
MakerNote NikonCaptureVersion (ASCII): COOLPIX P6000V1.0              
MakerNote NikonScan (Long): 3292
MakerNote NoiseReduction (ASCII): OFF 
MakerNote Quality (ASCII): FINE   
MakerNote RetouchHistory (Short): [0, 0, 0, 0, 0, 0]
MakerNote Saturation (ASCII): NORMAL
MakerNote Scene Assist (ASCII):                     
MakerNote SceneMode (ASCII):                
MakerNote ShotInfo (Undefined): [0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 67, 0, 0]
MakerNote Tag 0x000A (Ratio): 9321/1000
MakerNote Tag 0x0021 (Undefined): [1, 0, 64, 1, 240, 0, 0, 0]
MakerNote Tag 0x0029 (Short): [0, 0]
MakerNote Tag 0x002F (Short): 0
MakerNote Tag 0x009B (Short): [0, 0]
MakerNote Tag 0x009D (Short): 0
MakerNote Tag 0x00B2 (ASCII): NORMAL  
MakerNote Tag 0x00BD (Undefined): [48, 49, 48, 48, 83, 84, 65, 78, 68, 65, 82, 68, 32, 32, 32, 0, 0, 0, 0, 0, ... ]
MakerNote ToneCompensation (ASCII): NORMAL  
MakerNote Whitebalance (ASCII): AUTO        
Thumbnail Compression (Short): JPEG (old-style)
Thumbnail JPEGInterchangeFormat (Long): 4548
Thumbnail JPEGInterchangeFormatLength (Long): 6702
Thumbnail ResolutionUnit (Short): Pixels/Inch
Thumbnail XResolution (Ratio): 72
Thumbnail YResolution (Ratio): 72
```

**Comment by ludoo0d0a** [comment]
I investigated, retried, read doc, compared with other exif parser and it's ok now for these images.
May be I mixed images with no gps data in my tests, not clear...

You can close this issue for me.
thanks

**Comment by ludoo0d0a** [comment]
FYI: I found again the issue around GPS with 0 values.
it was only on an emulator with Android S. only data relevant to gps section were nullified. (strange behavior)
Tested with another one with Android R : it is ok
unit tests are ok.

**Comment by bigflood** [comment]
@ludoo0d0a thanks
